import './App.css';
import './Resualt.css';
import PopularSportCar from './PopularSportCar'
import { useState } from 'react'
import  McLaren from './imgFolder/Screenshot (23).png'
import  CorvetteC8 from './imgFolder/c84.jpg'
import  FerrariSF90 from './imgFolder/Red_2019_Ferrari_SF90_Stradale_(48264238897)_(cropped).jpg'
import  GTR35 from './imgFolder/GtR35.webp'
import lamborghiniSVJ1 from './imgFolder/svj1.webp'
import  MustangGT500 from './imgFolder/Mustang.jpg'
import  Dodge from './imgFolder/dodge kit.jpg'
import  camoryZl1 from './imgFolder/zl12.webp'
import  DodgeViper from './imgFolder/viper.jpg'
import  ToyotaSupra from './imgFolder/2 (1).jpg'
import  BugattiChiron from './imgFolder/Screenshot (31).png'
import hucan34  from './imgFolder/hucan34.jpg'
import hucanSTO   from './imgFolder/STO.jpg'
import bmwM4   from './imgFolder/bmwM4.jpg'
import bmwI8   from './imgFolder/BmwI8.webp'
import KoenigseggGemera  from './imgFolder/KoenigseggGemera.jpg'
import All from './All'
import FilterPrice from './FilterPrice'
import Contactus from './Contactus'
import porsche911 from './imgFolder/porsche911.jpg'
import Gclass63 from './imgFolder/Gclass.jpg'
import Urus from './imgFolder/Urus.jpg'
import Header from './Header';
import Resualt from './Resualt'
import FilterPrice2 from './FilterPrice.css';
import SearchCarinfo1 from './SearchCarinfo1.css'
import SearchinfoHeader from './SearchinfoHeader.css'
import SideBar from './SiderBar'
import SideBar7 from './SideBar.css'
import ContactusC from './Contactus.css'

import {  Router , Routes , Route   } from 'react-router-dom';
function App() {
  const [ Caritem , setCaritem ] = useState(
     [
      {
        "CarType" : "suv",
         "id": 127,    
         "title":   "Mercedes-AMG G63",
         "price1" :160000,
         "price" :  " $160,000",
        "Type"  : "SUV OFF ROAD",
         "Engin":   " 4.0-litre V8 Biturbo ",
        "Torque":  "850 Nm",
      "Horsepower":  "577 hp",
      "Acceleration":  "  3.9-second ",
      "storage"  :  "1,246 litres Total",
      "Transmission" : "9-speed automatic AMG SPEEDSHIFT TCT 9G",         
          "TopSpeed" : "130mph.",
          "person":  "7",
         "image": Gclass63,
         "Special":" Mafia Desing with Rooft Door ",
         "href" : "https://youtu.be/EyC3--JrTBc",
         "Carlogoname" : "Mercedes",
         "CarLogo" :"https://cdn.freebiesupply.com/logos/thumbs/2x/mercedes-benz-9-logo.png",
         "Madein" : "Germany",
 },
      {
        "CarType" : "suv",
         "id": 128,    
         "title":   "Lamborghini URUS",
         "price1" :230000 ,
         "price" :  " $230,000 ",
        "Type"  : "SUV Sport",
         "Engin":   " 4.0-liter twin-turbocharged V-8  ",
        "Torque":  "850 Nm",
      "Horsepower":  "641 hp",
      "Acceleration":  "  3.2-second ",
      "storage"  :  " 1596 litres,",
      "Transmission" : "8-speed ZF 8HP automatic",         
          "TopSpeed" : "305 km.",
          "person":  "5",
         "image": Urus,
         "Special":"Sport SUV ",
         "href" : "https://youtu.be/i8g_mW-q6Ic",
         "Carlogoname" : "lamborghini",
         "CarLogo" :"https://www.carlogos.org/car-logos/lamborghini-logo-1100x1200.png",
         "Madein" : "Italy",
 },

      {
       "CarType" : "sport",
        "id": 126,    
        "title":   "Porsche 911 turbo s stinger",
        "price1" : 207000,
        "price" :  " $207,000",
       "Type"  : "Caute Sport",
        "Engin":   " 3.8 L 6-cylinder horizontally opposed engine with VTG twin-turbo ",
       "Torque":  "800 Nm",
     "Horsepower":  "640 hp",
     "Acceleration":  " 2.2-second ",
     "storage"  :  "163 litres",
        "Transmission" : "8-speed PDK",
         "TopSpeed" : "205 mph.",
         "person":  "4",
        "image": porsche911,
        "Special":" Cute Desing",
        "href" : "https://youtu.be/1mPmCDS66Qc",
        "Carlogoname" : "porsche",
        "CarLogo" :"https://logos-world.net/wp-content/uploads/2021/04/Porsche-Logo.png",
        "Madein" : "Germany",
},
{
  "CarType" : "sport",  
  "id": 129,    
  "title":   "Koenigsegg Gemera",
  "price1" : 1700000 ,
  "price" :  "$1.7 million",
 "Type"  : "Super Sport Family Hypercar",
  "Engin":   "2.0 L TFG twin-turbocharged I3 · 3 electric motors placed both rear wheels and one on crankshaft 3-Cylinder",
 "Torque":  "3500 Nm",
"Horsepower":  "1,700 hp",
"Acceleration":  " 0 to 60 mph in 3.5 sec",
"storage"  :  "200 litres from the boot and frunk",
  "Transmission" : "Single-Speed Koenigsegg Direct Drive (KDD)",
   "TopSpeed" : "248mph",
   "person":  "4",
  "image": KoenigseggGemera,
  "Special":" 90deg door with 4-seat",
  "href" : "https://youtu.be/G6Cgj4PWA-o",
  "Carlogoname" : "Koenigsegg",
  "CarLogo" :"https://www.carlogos.org/logo/Koenigsegg-logo-1994-2048x2048.png" ,
  "Madein" : "Sweden",
},       
      {
        "CarType" : "sport",
        "id": 125,    
        "title":   "Bmw i8",
        "price1" : 147500,
        "price" :  "$147,500",
       "Type"  : "plug-in hybrid sports car",
        "Engin":   "turbocharged 1.5-liter three-cylinder gas engine with an 11.6-kWh battery pack and two electric motors",
       "Torque":  "420 lb-ft of torque",
     "Horsepower":  "   369hp. ",
     "Acceleration":  "0-60mph in 4.2 seconds. ",
     "storage"  :  " 83 litres ",
        "Transmission" : " Aisin F21-360 FT EOP.",
         "TopSpeed" : "155mph",
         "person":  " 4",
        "image": bmwI8,
        "Special":"Butterfly doors",
        "href" : "https://youtu.be/dhMuTlUVaFY",
        "Carlogoname" : "Bmw",
        "CarLogo" :"https://www.carlogos.org/car-logos/bmw-logo-1997-1200x1200.png",
        "Madein" : "Germany",
},
      {
        "CarType" : "sport",
        "id": 124,    
        "title":   "Bmw M4 CSL",
        "price1" : 139900,
        "price" :  "$139,900",
       "Type"  : " Sport",
        "Engin":   "3.0-litre twin-turbocharged straight-six engine ",
       "Torque":  "(649 Newton-meters) of torque available from 2,750 to 5,950 rpm.",
     "Horsepower":  "  550hp. ",
     "Acceleration":  "0-60mph in 3.7 seconds ",
     "storage"  :  " 83 litres ",
        "Transmission" : " 8-speed automatic transmission",
         "TopSpeed" : "191mph.",
         "person":  "2",
        "image": bmwM4,
        "Special":"body Design",
        "href" : "https://youtu.be/Y2odS-nK3uQ",
        "Carlogoname" : "Bmw",
        "CarLogo" :"https://www.carlogos.org/car-logos/bmw-logo-1997-1200x1200.png" ,
        "Madein" : "Germany",
},
      {
        "CarType" : "sport",
        "id": 123,    
        "title":   "lamborghini Huracan STO",
        "price1" : 327838,
        "price" :  "  $327,838",
       "Type"  : "Super Sport",
        "Engin":   "naturally aspirated V-10 engine",
       "Torque":  "565 Nm at 6,500 rpm.",
     "Horsepower":  "  640 hp.",
     "Acceleration":  " 0-100 km/h (MPH 0-62)3.0 s. ",
     "storage"  :  " 83 litres ",
        "Transmission" : " seven-speed dual-clutch automatic",
         "TopSpeed" : "310 km/h.",
         "person":  " 2",
        "image": hucanSTO,
        "Special":"body Design",
        "href" : "https://youtu.be/5MU-b8pm6J0",
        "Carlogoname" : "lamborghini",
        "CarLogo" :"https://www.carlogos.org/car-logos/lamborghini-logo-1100x1200.png" ,
        "Madein" : "Italy",

},
      {
        "CarType" : "sport",
                    "id": 122,    
                    "title":   "lamborghini Huracan",
                    "price1" : 206485,
                    "price" :  "  $206,485",
                   "Type"  : "Super Sport",
                    "Engin":   "V10 5.2 Liter.",
                   "Torque":  "443@6,500",
                 "Horsepower":  "602hp.",
                 "Acceleration":  "0-100 km/h (MPH 0-62)2.9 s. ",
                 "storage"  :  " 60 to 70 litres ",
                    "Transmission" : " 7-speed dual-clutch automatic.",
                     "TopSpeed" : "201 mph.",
                     "person":  " 2",
                    "image": hucan34,
                    "Special":"body Design",
                    "href" : "https://youtu.be/1HpliMCHFSY",
                    "Carlogoname" : "lamborghini",
                    "CarLogo" :"https://www.carlogos.org/car-logos/lamborghini-logo-1100x1200.png" ,
                    "Madein" : "Italy",
      },
      {
        "CarType" : "sport",
          "id": 111,    
          "title":   "McLaren 720S",
          "price1" :   284745,
          "price" :  "  $284,745.",
         "Type"  : "Base, Luxury, and Performance",
          "Engin":   "4.0-liter twin-turbo V8.",
         "Torque":  "568 lb-ft.",
       "Horsepower":  "710 hp.",
       "Acceleration":  "0 to 60 : 2.8s ",
       "storage"  :  "150 liters",
          "Transmission" : " 7-speed dual-clutch automatic.",
           "TopSpeed" : "212 mph.",
           "person":  " 2",
          "image": McLaren,
          "Special":"Butterfly doors",
          "href" : "https://youtu.be/Zbzqx-hGOCg",
          "Carlogoname" : "McLaren",
          "CarLogo" :"https://www.pngall.com/wp-content/uploads/2016/04/McLaren-Logo-Transparent.png",
          "Madein" : "England",
      },
      {
        "CarType" : "sport",
          "id": 112,    
          "title":   "Chevy Chevrolet C8",
          "price1" :76150,
          "price" :  "$76,150.",
         "Type"  : "1LT,Coupe or a Convertible body",
          "Engin":   "6.2L V8 LT2 engine.",
         "Torque":  "465 lb-ft of torque.",
       "Horsepower":  "490hp .",
       "Acceleration":  "0 to 60 : 2.9s ",
       "storage"  :  "70 litres",
          "Transmission" : "Tremec TR-9080 DCT 8-speed dual clutch ",
           "TopSpeed" : "194 mph ",
           "person":  " 2",
           "Special":"Rear Camera Mirror* Rear park assist* and HD rear vision camera*",
          "image": CorvetteC8,
          "href" : "https://youtu.be/7n3ITV6T2j4",
          "Carlogoname" : "Chevrolet",
          "CarLogo" :"https://www.carlogos.org/logo/Chevrolet-logo-2013-2560x1440.png" ,
          "Madein" : "United States",
      },
      {
        "CarType" : "sport",
          "id": 113,    
          "title":   "Ferrari SF90",
          "price1" :625000,
          "price" :  "  $625,000",
         "Type"  : "Super Sport",
          "Engin":   "4.0 l V8",
         "Torque":  "590 lb·ft @ 6,000 rpm (800 N·m)",
       "Horsepower":  "769 hp @ 7,500 rpm (573 kW)",
       "Acceleration":  "0  to 60 : 2.0s  ",
       "storage"  :  "50 litres",
          "Transmission" : " 8-speed dual-clutch",
           "TopSpeed" : "211 mph",
           "person":  " 2",
           "Special":"interior ",
          "image":FerrariSF90,
          "href" : "https://youtu.be/AL-GDDN5Y-0",
          "Carlogoname" : "Ferrari",
          "CarLogo" :"https://www.senkyr.cz/data/katalog/kategorie/712-ferrari_logo.png" ,
          "Madein" : "Italy",
      },
      {
        "CarType" : "sport",
          "id": 114,    
          "title":   "Nissan GTR 35",
          "price1" :115000,
          "price" :  "$115,000",
         "Type"  : "unique style and performance",
          "Engin":   "3.8-litre twin-turbo V6",
         "Torque":  " 419kW/632Nm",
       "Horsepower":  "710hp",
       "Acceleration":  "   0 to 60  2.5s",
       "storage"  :  " 74 litres",
          "Transmission" : " six-speed dual-clutch automatic.",
           "TopSpeed" : "196 mph.",
           "person":  " 4",
           "Special":"Price to Performent ",
          "image":GTR35,
          "href" : "https://youtu.be/vlDOjTaaEdA",
          "Carlogoname" : "Nissan",
          "CarLogo" :"https://upload.wikimedia.org/wikipedia/commons/8/8c/Nissan_logo.png",
          "Madein" : "Japn",
      },
      {
        "CarType" : "sport",
          "id": 115,    
          "title":   "Lamborghini Aventador SVJ",
          "price1" :517770,
          "price" :  "  $517,770",
         "Type"  : " SuperSport + and bodyDesign",
          "Engin":   "6.5L V12.",
         "Torque":  "443@6,500",
       "Horsepower":  "770 hp",
       "Acceleration":  " 0 to 60 : 2.7s.",
       "storage"  :  "90 liters",
          "Transmission" : "7-Speed Single Clutch",
           "TopSpeed" : "217+ mph.",
           "person":  " 2",
           "Special":"V12 + Design  ",
          "image":lamborghiniSVJ1,
          "href" : "https://youtu.be/42YbTTK7ESc",
          "Carlogoname" : "lamborghini",
          "CarLogo" :"https://www.carlogos.org/car-logos/lamborghini-logo-1100x1200.png" ,
          "Madein" : "Italy",         
      },
      {
        "CarType" : "sport",
          "id": 116,    
          "title":   "Mustang GT500",
          "price1" :70000,
          "price" :  "$70,000",
         "Type"  : "Sport muscle Coupe",
          "Engin":   "5.2l V8",
         "Torque":  "625 lb·ft @ 5,000 rpm (847 N·m)",
       "Horsepower":  "760 hp",
       "Acceleration":  " 0 to 60 : 3.3s",
       "storage"  :  "445 litres",
          "Transmission" : "7-Speed Dual-Clutch",
           "TopSpeed" : "180 mph.",
           "Special":"Cheap Price  ",
           "person":  " 2",
          "image":MustangGT500,
          "href" : "https://youtu.be/PWAPQ2fAl5Q",
          "Carlogoname" : "Ford",
          "CarLogo" :"https://www.carlogos.org/car-logos/ford-logo-2017.png" ,
          "Madein" : "United States", 
      },
      {
        "CarType" : "sport",
          "id": 117,    
          "title":    "Dodge Hellcat Demon With Body Kit",
          "price1" :   84995,
          "price" :  " $84,995",
         "Type"  : "Muscle",
          "Engin":   "6.2 l V8",
         "Torque":  "717 lb·ft @ 4,500 rpm (972 N·m)",
       "Horsepower":  "808 hp ",
       "Acceleration":  "0 to 60 : 2.3 seconds ",
       "storage"  :  "170 liters",
          "Transmission" : " Transmission =915663 · Hurst Billet/Plus Pistol Grip Automatic Shift ... ",
           "TopSpeed" : "196 mph",
           "person":  "4",
           "Special":"Supercharged ",
          "image":Dodge,
          "href" : "https://youtu.be/iHcJr60y6aw",
          "Carlogoname" : "Dodge",
          "CarLogo" :"https://www.carlogos.org/logo/Dodge-logo-2011-3840x2160.png",
          "Madein" : "United States", 
      },
      {
        "CarType" : "sport",
          "id": 118,    
          "title":   "Chevrolet Camaro Zl1",
          "price1" :  65000,
          "price" :  "$65,000",
         "Type"  : "muscle Coupe ",
          "Engin":   "6.2L V8 engine",
         "Torque":  "650 lb-ft @ 3,600 rpm",
       "Horsepower":  "650 hp ",
       "Acceleration":  "0 to 60 : 5.4 s ",
       "storage"  :  "150 liters",
          "Transmission" : "Available paddle-shift 10-speed automatic ... ",
           "TopSpeed" : "198 mph ",
           "person":  " 4",
           "Special":"Supercharged ",
          "image":camoryZl1,
          "href" : "https://youtu.be/bSWGJsDIFY4",
          "Carlogoname" : "Chevrolet",
          "CarLogo" :"https://www.carlogos.org/logo/Chevrolet-logo-2013-2560x1440.png",
          "Madein" : "United States",  
      },
      {
        "CarType" : "sport",
          "id": 119,    
          "title":   "Dodge Viper GTS-R",
          "price1" :  294857,
          "price" :  "$294,857",
         "Type"  : "Sport Coupe",
          "Engin":   "Viper 8.0-liter (7,998 cc) V10 naturally-aspirated, front-engined, rear-wheel drive",
         "Torque":  "729 lb⋅ft (988 N⋅m) torque",
       "Horsepower":  "709 hp",
       "Acceleration":  "0 to 60  3.3 sec, ",
       "storage"  :  "415 litres.",
          "Transmission" : " Transmission = BorgWarner T56 6-speed manual",
           "TopSpeed" : "185 mph",
           "Special":"Unknow ",
           "person":  " 2",
          "image":DodgeViper,
          "href" : "https://youtu.be/HruMwfBotzs",
          "Carlogoname" : "Dodge",
          "CarLogo" :"https://www.carlogos.org/logo/Dodge-logo-2011-3840x2160.png",
          "Madein" : "United States", 
      },
      {
        "CarType" : "sport",
          "id": 120,    
          "title":   "Toyota Supra ",
          "price1" :   55374,
          "price" :  "$55,374",
         "Type"  : "Sport Coupe",
          "Engin":   "2.0-litre engine with twin-scroll turbocharger.	",
         "Torque":  "400 Nm of torque.",
       "Horsepower":  "335 hp",
       "Acceleration":  "  Acceleration = 0 to 60   4.1 s, ",
       "storage"  :  "290-litre",
          "Transmission" : "(MT) option ... At launch",
           "TopSpeed" : "165 mph ",
           "Special":"Toyota Supra Next Gen ",
           "person":  " 2",
          "image":ToyotaSupra,
          "href" : "https://youtu.be/FblJGCdMlds",
          "Carlogoname" : "Toyota",
          "CarLogo" :"https://www.pngall.com/wp-content/uploads/2016/04/Toyota-Logo-Free-Download-PNG.png" ,
          "Madein" : "Japn",
      },
      {
        "CarType" : "sport",
          "id": 121,    
          "title":   "Bugatti Chiron ",
          "price1" :   3987000,
          "price" :  "$3.9 million",
         "Type"  : "Super Sport + mid-size sports car",
          "Engin":   "8.0 l W16 	Turbocharged	",
         "Torque":  "1,180 lb·ft @ 2,000 : 6,000 rpm (1,600 N·m) ",
       "Horsepower":  "1500  hp",
       "Acceleration":  "0 to 60   2.4 seconds, ",
       "storage"  :  " 44 litres.",
          "Transmission" : "7-speed dual-clutch automatic",
           "TopSpeed" : "273 mph ",
           "Special":"million Car  ",
           "person":  " 2",
          "image":BugattiChiron,
          "href" : "https://youtu.be/FR8iIMPNqYk",
          "Carlogoname" : "Bugatti",
          "CarLogo" :"https://www.carlogos.org/logo/Bugatti-logo-2560x1440.png",
          "Madein" : "France",
      },
      ]
  )
const [FilterCar ,setFilterCar ] = useState([]);
const [Carfilter , setcarfilter ] = useState([])
  return (
    <div className="App">
    
        <Header
      Caritem={Caritem}
      setCaritem={setCaritem}
      FilterCar={FilterCar}
      setFilterCar={setFilterCar}
      setcarfilter={setcarfilter}
      />    
      <Resualt/>  
      <SideBar Caritem={Caritem} setcarfilter={setcarfilter}/>
    <Routes> 
  <Route  path="/"   element={  <PopularSportCar Caritem={Caritem} FilterCar={FilterCar}/>  }  />      
      <Route  path="/All"  element={<All Caritem={Caritem} FilterCar={FilterCar}/>} />    
      <Route  path='/FilterPrice' element={<FilterPrice Caritem={Caritem} Carfilter={Carfilter} setcarfilter={setcarfilter}/>} />
      <Route  path='/Contactus' element={<Contactus/>} />
   </Routes>      
        
   
  
    </div>
   
   
  );
}

export default App;
